const $=id=>document.getElementById(id);
const widget=$('widget'),cover=$('cover');
let state={progress_ms:0,duration_ms:0,playing:false},received=performance.now(),image='';
const time=ms=>{const s=Math.floor(Math.max(0,ms)/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
function scrollText(){document.querySelectorAll('.scroll-text').forEach(el=>{const distance=Math.max(0,el.scrollWidth-el.parentElement.clientWidth);el.classList.toggle('scrolling',distance>1);el.style.setProperty('--scroll-distance',`${distance}px`);el.style.setProperty('--scroll-duration',`${Math.max(5,Math.min(18,distance/30))}s`);});}
function fallback(){widget.style.background='linear-gradient(135deg,#983dce,#150b27)';$('progress-fill').style.background='#d18bff';}
function colors(url){const sample=new Image();sample.crossOrigin='anonymous';sample.onload=()=>{if(url!==image)return;try{const canvas=document.createElement('canvas');canvas.width=canvas.height=30;const ctx=canvas.getContext('2d');ctx.drawImage(sample,0,0,30,30);const pixels=ctx.getImageData(0,0,30,30).data;const rgb=[0,0,0];for(let i=0;i<pixels.length;i+=4)for(let k=0;k<3;k++)rgb[k]+=pixels[i+k];const average=rgb.map(c=>Math.round(c/(pixels.length/4)));const color=delta=>`rgb(${average.map(c=>Math.max(0,Math.min(255,c+delta))).join(',')})`;widget.style.background=`linear-gradient(135deg,${color(-55)},${color(-20)})`;$('progress-fill').style.background=color(40);}catch{fallback();}};sample.onerror=fallback;sample.src=url;}
function apply(data){state=data;received=performance.now();$('title').textContent=data.title||'Kass';$('artist').textContent=(data.artist||'Artista sconosciuto')+(data.track_id&&!data.playing?' · In pausa':'');const next=data.image||'/kass.svg';if(image!==next){image=next;cover.src=next;if(next==='/kass.svg')fallback();else colors(next);}cover.style.display='block';scrollText();update();}
cover.onerror=()=>{if(cover.getAttribute('src')!=='/kass.svg'){image='/kass.svg';cover.src=image;}fallback();};
function update(){const elapsed=state.playing?performance.now()-received:0;const progress=Math.min(state.duration_ms||0,(state.progress_ms||0)+elapsed);$('currentTime').textContent=time(progress);$('totalTime').textContent=time(state.duration_ms||0);$('progress-fill').style.width=`${state.duration_ms?Math.min(100,progress/state.duration_ms*100):0}%`;}
async function poll(){try{const response=await fetch('/api/now-playing',{cache:'no-store'});if(!response.ok)throw Error();apply(await response.json());}catch{apply({title:'Kass non disponibile',artist:'Apri Kass per mostrare la tua musica',image:'/kass.svg',playing:false,progress_ms:0,duration_ms:0});}finally{setTimeout(poll,1500);}}
window.addEventListener('resize',scrollText);if(window.ResizeObserver)new ResizeObserver(scrollText).observe(widget);
setInterval(update,250);fallback();poll();
